FROM node:latest

EXPOSE 8080
WORKDIR /app/client

COPY ./client/config config/
COPY ./client/.babelrc .
COPY ./client/package.json .
COPY ./client/package-lock.json .

RUN npm i --no-progress --ignore-optional

CMD npm start