FROM python:latest

# install robot
RUN pip3 install robotframework

# Install Libraries

RUN pip3 install robotframework-mqttlibrary && \
    pip3 install RESTinstance && \
    pip3 install robotframework-docker && \
    pip3 install rethinkdb

WORKDIR /root