FROM node:latest


WORKDIR /app/api
EXPOSE 3000

COPY ./api/dist-api .
COPY ./api/package.json .
COPY ./api/package-lock.json .
COPY ./api/.babelrc .

RUN npm i --no-progress --ignore-optional

CMD npm run dev:watch
